global SECRET_KEY
SECRET_KEY = ""

global GITHUB_TOKEN
GITHUB_TOKEN = ""

global GOOGLE_AI_TOKEN
GOOGLE_AI_TOKEN = ""

global MISTRAL_API_KEY
MISTRAL_API_KEY = ""

global GITHUB_CLIENT_ID
GITHUB_CLIENT_ID = ""

global GITHUB_CLIENT_SECRET
GITHUB_CLIENT_SECRET = ""
