name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: chriswebb09
  GITHUB_REPOSITORY: DirectReport
  GITHUB_TOKEN: ${{ secrets.GH_PAGES }}

on: 
  push:
    branches: [ main ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
    

    steps:
    
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${GH_TOKEN}
        run: |
          set -x
          apt-get update
          apt-get install -y git rsync python-sphinx python-sphinx-rtd-theme
          git clone 'https://token:${GH_TOKEN}@github.com/chriswebb09/DirectReport.git' .
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${GH_TOKEN}
        run: "docs/buildDocs.sh"
        shell: bash
