name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: chriswebb09
  GITHUB_REPOSITORY: DirectReport
  GITHUB_TOKEN: ${{ secrets.GH_PAGE }}

on: 
  push:
    branches: [ main ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
    

    steps:
    
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGE }}
        run: |
          set -x
          git config --global user.email "chris.webb5249@gmail.com"
          git config --global user.name "chriswebb09"
          apt-get update
          apt-get install -y git rsync python-sphinx python-sphinx-rtd-theme
          git clone "https://token:$GITHUB_TOKEN@github.com/chriswebb9/DirectReport.git" .
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGE }}
        run: "docs/buildDocs.sh"
        shell: bash
